#version: '3.8'

services:
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    image: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/home/mlflowuser
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    networks:
      - ml-monitoring

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ml-monitoring

  pushgateway:
    image: prom/pushgateway:v1.6.0
    ports:
      - "9091:9091"
    networks:
      - ml-monitoring

  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    image: liquidity-trainer
    volumes:
      - ./data:/app/data
      - ./trainer:/app
    networks:
      - ml-monitoring
    environment:
      PROMETHEUS_PUSHGATEWAY_URL: "http://pushgateway:9091"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
      DATA_PATH: "/app/data/preprocess"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - ml-monitoring
    depends_on:
      - prometheus

networks:
  ml-monitoring:
    driver: bridge